import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { TeamCard } from '../components/TeamCard'
import { api } from '../utils/api'
import { type Team } from '../utils/types'

type Props = {
  teams: Team[]
}
export const getStaticProps: GetStaticProps<Props> = async () => {
  
  const teams = await api.getTeams()
  return {
    props: {
      teams
    }
  }
}
const Home: NextPage<Props> = ({teams}) => {

  return (
    <div>
      <Head>
        <title>🏀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        {teams.map(team => (
          <TeamCard key={team.TeamID} team={team}/>
        ))}
      </section>
    </div>
  )
}

export default Home
